# TODO: merge this into release.yml once we know it works

name: Build appx

on:
  workflow_dispatch:

jobs:
  build-appx:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install Dependencies
      run: npm ci
    - name: Download Library Files
      run: npm run fetch
    - name: Compile and package
      run: npm run dist -- --windows appx --publish never --x64 --ia32
      env:
        NODE_OPTIONS: --max-old-space-size=4096
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: appx
        path: dist/*.appx
