name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install Dependencies
      run: npm ci
    - name: Download Library Files
      run: npm run fetch
    - name: Compile
      run: npm run compile
      env:
        NODE_OPTIONS: --max-old-space-size=4096
        TW_ENABLE_UPDATE_CHECKER: "1"
    - name: Build
      run: npx --no-install electron-builder --publish never
