name: Build (Auto)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install Dependencies
      run: npm ci
    - name: Compile
      run: npm run compile
      env:
        NODE_OPTIONS: --max-old-space-size=4096
    - name: Package
      run: npx electron-builder --linux tar.gz --publish never
      env:
        NODE_OPTIONS: --max-old-space-size=4096
    - uses: actions/upload-artifact@v2
      with:
        name: Linux tar.gz
        path: dist/*.tar.gz
