name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install Dependencies
      run: npm ci
    - name: Download Library Files
      run: npm run fetch
    - name: Compile and package
      run: npm run dist -- --publish always
      env:
        NODE_OPTIONS: --max-old-space-size=4096
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TW_ENABLE_UPDATE_CHECKER: "1"
    - name: Package appx
      if: runner.os == 'Windows'
      run: npm run dist -- --windows appx --publish never --x64 --ia32
      env:
        NODE_OPTIONS: --max-old-space-size=4096
        TW_EXTRA_BUILD_INFO: "GH-Release"
    - name: Upload artifacts
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v2
      with:
        name: appx
        path: dist/*.appx
