name: Update scratch-gui

on: workflow_dispatch

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci
    - run: npm install scratch-gui@github:TurboWarp/scratch-gui#desktop
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update scratch-gui
